# -*- coding: utf-8 -*-
"""CIE - 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g99oRX1om8eIm46a9kxM8t4QMqGJACTb
"""

import pandas as pd
data = pd.read_csv("/content/mtcars.csv")
print(data)

import matplotlib.pyplot as plt
plt.hist(data['mpg'], bins=10, color='skyblue', edgecolor='black')
plt.title('Frequency Distribution of Miles per Gallon (mpg)')
plt.xlabel('Miles per Gallon (mpg)')
plt.ylabel('Frequency')
plt.grid(False)
plt.show()

import matplotlib.pyplot as plt
plt.scatter(data['wt'], data['mpg'], color='r', alpha=0.5)
plt.title('Relationship between Car Weight and MPG')
plt.xlabel('Weight of the Car')
plt.ylabel('Miles per Gallon (MPG)')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
tc = data.groupby('model').size().nlargest(5)
tc.plot(kind='bar', color='skyblue')
plt.title('Frequency Distribution of Transmission Types')
plt.xlabel('types of cars')
plt.ylabel('Frequency')
plt.show()

import matplotlib.pyplot as plt
data.boxplot(column='mpg', by='cyl', grid=False, color='r', figsize=(10, 6))
plt.title('Box and Whisker Plot of MPG by Cylinder Count')
plt.xlabel('Number of Cylinders')
plt.ylabel('Miles per Gallon (MPG)')
plt.show()

data.mpg.describe()

import pandas as pd
data = pd.read_csv("/content/tips.csv")
print(data)

avg = data.groupby('day')['total_bill'].sum().sort_index()
print(avg)

filtered_data = data[data["tip"] > 5]
print(filtered_data)

from functools import reduce
total_tip = reduce(lambda x, y: x + y, data["tip"])
print("Total tips:", total_tip)